apiVersion: v1
kind: PersistentVolume
metadata:
  name: geds-cache
  namespace: default
spec:
  storageClassName: geds-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/5G"
    type: DirectoryOrCreate
