apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
spec:
  containers:
    - name: influxdb
      image: raulgracia/pravega-influxdb:latest
      ports:
        - containerPort: 8086
          name: influxdb-port
